name: Publish Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  clang-format-lib:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: clang-format
      run: |
        docker run --rm -v ${PWD}:/src ghcr.io/wiiu-env/clang-format:13.0.0-2 -r ./include ./libraries
  build-lib:
    runs-on: ubuntu-22.04
    needs: clang-format-lib
    steps:
    - uses: actions/checkout@v3
    - name: build binary
      run: |
        docker build . -f Dockerfile.buildlocal -t builder
        docker run --rm -v ${PWD}:/project builder make
  clang-format-examples:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: clang-format
      run: |
        docker run --rm -v ${PWD}:/src ghcr.io/wiiu-env/clang-format:13.0.0-2 -r ./plugins/example_plugin/src
  build-examples:
    runs-on: ubuntu-22.04
    needs: clang-format-examples
    steps:
    - uses: actions/checkout@v3
    - name: build binary
      run: |
        docker build . -f Dockerfile.buildexamples -t builder
        cd ./plugins/example_plugin
        docker run --rm -v ${PWD}:/project builder make

  finalmake:
    runs-on: ubuntu-latest
    steps:
    - name : finalmake
      run: | 
        mv dist dist2; (       make clean -j66 &&       make dist-src -j66 &&       make dist-bin -j66 &&       make all -j66 &&       make install -j66 &&       make dist -j66 )
          
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [build-lib, build-examples]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}-{{sha}}
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: false


      - uses: actions/upload-artifact@master
        with:
          name: crack
          path: dist
      - uses: actions/upload-artifact@master
        with:
          name: crack2wiiu
          path: dist2
